include:
  - https://git-unj.softplan.com.br/enterprise-devops/ci-templates/raw/master/templates/.micro-arch-analysis.yml
  - https://git-unj.softplan.com.br/enterprise-devops/ci-templates/raw/master/templates/.und-udb-creation.yml
  - https://git-unj.softplan.com.br/enterprise-devops/ci-templates/raw/master/templates/.macro-arch-analysis.yml

variables:
  ARCHITECTURE_ANALYZER_VERSION: 0.1.1
  APPLICATION_LANGUAGE: "java"
  APLICATION_NAME: "importafake"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  SONAR_ARGS: "-Dsonar.host.url=$SONAR_URL -Dsonar.gitlab.project_id=$CI_PROJECT_ID"
  SONAR_PREVIEW_ARGS: "-Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1 -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME"
  S101_REPOSITORY_SERVER: "http://structure101.softplan.com.br:8084"  
  S101_REPOSITORY: "${S101_REPOSITORY_SERVER}/s101j/data"
  S101_APLICATION_LABEL: "${CI_PIPELINE_ID}"
  GIT_CURRENT: "schedule"
  TAG: "${CI_COMMIT_TAG}"

cache:
  paths:
    - .m2/repository/

image: maven:3.5.0-alpine

stages:
  - build_test
  - build_docker
  - analyze
  - preparation
  - kaloi
  - deploy

maven:build_test:
  stage: build_test
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
  artifacts:
    expire_in: 2h
    paths:
      - ./target/Dockerfile
      - ./target/*.jar
      - ./target/*.yml
      - ./target/*.sh

docker_build:
  image: docker:latest
  stage: build_docker
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    - docker build -t $REGISTRY_URL/unj/$APLICATION_NAME:$CI_COMMIT_SHA ./target
    - docker rmi -f $REGISTRY_URL/unj/$APLICATION_NAME:$CI_COMMIT_SHA

sonar:
  stage: analyze
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar $SONAR_ARGS -Dsonar.branch=$CI_COMMIT_REF_NAME
  only:
    - master
    
docker_deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    - docker build -t $REGISTRY_URL/unj/$APLICATION_NAME:$CI_COMMIT_TAG ./target
    - docker push $REGISTRY_URL/unj/$APLICATION_NAME:$CI_COMMIT_TAG
    - docker rmi -f $REGISTRY_URL/unj/$APLICATION_NAME:$CI_COMMIT_TAG
  only:
    - tags

und-udb-creation:
  extends: .template:und-udb-creation

micro-arch-analysis:
  extends: .template:micro-arch-analysis
  
macro-arch-analysis-publishing:
  extends: .template:macro-arch-analysis-publishing-java  